# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/NVIDIA/gpu-monitoring-tools"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  branch = "master"
  name = "github.com/gpucloud/gohwloc"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.23.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "11.0.0"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.4.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.15.2"

[prune]
  go-tests = true
  unused-packages = true
