// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package vgpu

import (
	"sync"
)

// Ensure, that NvidiaPCIMock does implement NvidiaPCI.
// If this is not the case, regenerate this file with moq.
var _ NvidiaPCI = &NvidiaPCIMock{}

// NvidiaPCIMock is a mock implementation of NvidiaPCI.
//
//	func TestSomethingThatUsesNvidiaPCI(t *testing.T) {
//
//		// make and configure a mocked NvidiaPCI
//		mockedNvidiaPCI := &NvidiaPCIMock{
//			DevicesFunc: func() ([]*PCIDevice, error) {
//				panic("mock out the Devices method")
//			},
//		}
//
//		// use mockedNvidiaPCI in code that requires NvidiaPCI
//		// and then make assertions.
//
//	}
type NvidiaPCIMock struct {
	// DevicesFunc mocks the Devices method.
	DevicesFunc func() ([]*PCIDevice, error)

	// calls tracks calls to the methods.
	calls struct {
		// Devices holds details about calls to the Devices method.
		Devices []struct {
		}
	}
	lockDevices sync.RWMutex
}

// Devices calls DevicesFunc.
func (mock *NvidiaPCIMock) Devices() ([]*PCIDevice, error) {
	if mock.DevicesFunc == nil {
		panic("NvidiaPCIMock.DevicesFunc: method is nil but NvidiaPCI.Devices was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDevices.Lock()
	mock.calls.Devices = append(mock.calls.Devices, callInfo)
	mock.lockDevices.Unlock()
	return mock.DevicesFunc()
}

// DevicesCalls gets all the calls that were made to Devices.
// Check the length with:
//
//	len(mockedNvidiaPCI.DevicesCalls())
func (mock *NvidiaPCIMock) DevicesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDevices.RLock()
	calls = mock.calls.Devices
	mock.lockDevices.RUnlock()
	return calls
}
