// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package vgpu

import (
	"sync"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//	func TestSomethingThatUsesInterface(t *testing.T) {
//
//		// make and configure a mocked Interface
//		mockedInterface := &InterfaceMock{
//			DevicesFunc: func() ([]*Device, error) {
//				panic("mock out the Devices method")
//			},
//		}
//
//		// use mockedInterface in code that requires Interface
//		// and then make assertions.
//
//	}
type InterfaceMock struct {
	// DevicesFunc mocks the Devices method.
	DevicesFunc func() ([]*Device, error)

	// calls tracks calls to the methods.
	calls struct {
		// Devices holds details about calls to the Devices method.
		Devices []struct {
		}
	}
	lockDevices sync.RWMutex
}

// Devices calls DevicesFunc.
func (mock *InterfaceMock) Devices() ([]*Device, error) {
	if mock.DevicesFunc == nil {
		panic("InterfaceMock.DevicesFunc: method is nil but Interface.Devices was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDevices.Lock()
	mock.calls.Devices = append(mock.calls.Devices, callInfo)
	mock.lockDevices.Unlock()
	return mock.DevicesFunc()
}

// DevicesCalls gets all the calls that were made to Devices.
// Check the length with:
//
//	len(mockedInterface.DevicesCalls())
func (mock *InterfaceMock) DevicesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDevices.RLock()
	calls = mock.calls.Devices
	mock.lockDevices.RUnlock()
	return calls
}
