---
{{- $options := (include "nvidia-device-plugin.options" . | fromJson) }}
{{- if or $options.hasConfigMap .Values.gfd.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nvidia-device-plugin.fullname" . }}-role
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  {{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
  {{- include "nvidia-device-plugin.rule.openshiftSCC" . | nindent 2 }}
  {{- end }}
  {{- if .Values.gfd.enabled }}
  - apiGroups: ["nfd.k8s-sigs.io"]
    resources: ["nodefeatures"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  {{- end }}
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nvidia-device-plugin.fullname" . }}-role
  namespace: {{ include "nvidia-device-plugin.namespace" . }}
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  {{- include "nvidia-device-plugin.rule.openshiftSCC" . | nindent 2 }}
{{- end }}
{{- end }}
