{{- if .Values.nfd.enableNodeFeatureApi }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-feature-discovery
rules:
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - get
  - list
  - watch
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpu-feature-discovery
subjects:
- kind: ServiceAccount
  name: gpu-feature-discovery
  namespace: node-feature-discovery

{{- end }}
