apiVersion: v1
kind: Pod
metadata:
  name: pod1-shared
spec:
  restartPolicy: OnFailure
  containers:
  - image: nvcr.io/nvidia/cuda
    name: pod1-ctr
    command: ["sleep"]
    args: ["100000"]
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
        nvidia.com/sharedgpu: 2
