---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Build Image"
run-name: Build Image - ${{ github.ref_name }}

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    name: Build & Publish GHA Runner Image
    runs-on: cw-dind-medium
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set build vars
        id: metadata
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          TAG_PREFIX="ghcr.io/${{ github.repository }}"
          if [[ ${{ github.ref_name }} != 'coreweave' ]]; then
            TAG="${TAG_PREFIX}/dev:${SHORT_SHA}"
          else
            TAG="${TAG_PREFIX}/coreweave:${SHORT_SHA}"
          fi
          echo "Image will be published with tag ${TAG}"
          echo "IMAGE_TAG=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.metadata.outputs.IMAGE_TAG }}
          platforms: linux/amd64, linux/arm64
          file: ${{ github.workspace }}/deployments/container/Dockerfile.ubuntu

