name: Run pre sanity

# run this workflow for each commit
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
             
      - name: Build dev image
        run: make .build-image
      
      - name: Build
        run: make docker-build

      - name: Tests
        run: make docker-coverage

      - name: Checks
        run: make docker-check
